# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a1d7645012e4909b1ace37cd5cc8c5351e2fb62be5df43881cef926ae5aac8f83ee853fba8c6d8a021030cb5490ea3f347e3336936f6e744315b9163fa75f6

test:
  secret_key_base: 4dc02059708167d98ffd87ea1455eeb533df8df956e9a517f4d937da08c47aa653a90c96b7652c4cd4fc3102210a73e4ec3ce5f1a0bab8a7e0ca4e5f59b42ced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
